name: Playwright Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore ./Playwright-Seznam.cz.csproj

      - name: Build project
        run: dotnet build ./Playwright-Seznam.cz.csproj

      - name: Install Playwright browsers
        run: pwsh ./bin/Debug/net9.0/playwright.ps1 install --with-deps

      - name: Clean old traces & screenshots
        run: |
          rm -rf traces
          rm -rf test-results/screenshots

      - name: Run tests and generate TRX
        run: dotnet test ./Playwright-Seznam.cz.csproj --logger "trx;LogFileName=test_results.trx"

      - name: Upload TRX results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./TestResults/**/*.trx

      - name: Upload traces (only if exist)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: traces
          path: traces

      - name: Upload screenshots (only if exist)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: test-results/screenshots
